language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "6"
    - node_js: "4"
sudo: required # this seems to be required in order to use caches...
cache:
  directories:
    - node_modules
    - chrome
before_script:
  # fetch and extract Chrome if not cached
  - if [ ! -x chrome/opt/google/chrome/chrome ]; then
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
        dpkg -x google-chrome-stable_current_amd64.deb chrome &&
        rm -f google-chrome-stable_current_amd64.deb
    else
        echo 'Using cached Google Chrome';
    fi
  # dump the current versions
  - chrome/opt/google/chrome/chrome --version
  - npm list
  # prepare the headless environment
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start && sleep 5
  # start a fresh new Chrome instance
  - chrome/opt/google/chrome/chrome
        --user-data-dir=$(mktemp -d)
        --no-sandbox --no-first-run --disable-extensions --remote-debugging-port=9222
        about:blank &
  # wait for Chrome to start up
  - while ! curl http://localhost:9222 >/dev/null; do sleep 1; done
