language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "6"
    - node_js: "4"
cache:
  directories:
    - node_modules
    - chrome
before_script:
  - if [ ! -e chrome/ ]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && dpkg -x google-chrome-stable_current_amd64.deb chrome; fi
  - chrome/opt/google/chrome/chrome --version
  - npm list
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - chrome/opt/google/chrome/chrome --no-sandbox --no-first-run --disable-extensions --user-data-dir=$(mktemp -d) --remote-debugging-port=9222 about:blank &
  - sleep 5
